### Get all books
GET http://localhost:8080/api/books
Accept: application/json


### Search books
GET http://localhost:8080/api/books/search?title=java
Accept: application/json


### Create book
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Java Concurrency in Practice",
  "isbn": "9780321349606",
  "price": 42.90,
  "publicationDate": "2006-05-19"
}

### Create book 2
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Clean Architecture",
  "isbn": "978-12309876",
  "price": 25.99,
  "publicationDate": "2017-09-20"
}

### Create book with authors
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "Good Omens",
  "isbn": "9780060853983",
  "price": 12.99,
  "publicationDate": "1990-05-01",
  "authorIds": [
    "58515c73-0645-4ebf-a3ee-69a6e7ee5a38",
    "24e0ff2b-25fc-432f-9a26-68d46aaf8845"
  ]
}

### Create invalid book
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "title": "",
  "isbn": "",
  "price": -10
}

### Delete book
DELETE http://localhost:8080/api/books/49282b9f-f3b1-42d6-b05c-d4a635879364